version: 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: romanandreg/stack:latest

    steps:
      - checkout
      - run: apt-get update && apt-get install git -y
      - restore_cache:
          key: build-cache-{{ checksum "stack.yaml" }}
      - run: stack setup
      - run: stack build --only-dependencies -j1
      - run: stack install
      - save_cache:
          key: build-cache-{{ checksum "stack.yaml" }}
          paths:
            - /root/.stack
            - /root/.cabal
            - .stack-work
